### ISSUE TITLE
Could this runner be integrated with GitHub Actions?

### ISSUE THREAD

**Issue by adrienbrown2020** [microsoft/HydraLab#192]

**Comment by olivershen-wow** [comment]
Hi @adrienbrown2020, are you using Hydra Lab to test an Android app or an iOS app?

For Android app test only, we have an Gradle plugin ready for use, see details here: [Gradle plugin README](https://github.com/microsoft/HydraLab/blob/main/gradle_plugin/README.md).
You may add a new "Gradle Build Action" task in your Git Actions workflow, a sample of the yml content as below:
```
- name: Gradle Build Action
  uses: gradle/gradle-build-action@v2.4.1
  with:
    # Gradle command line arguments (supports multi-line input)
    arguments: [your gradle arguments after command "gradle"]
```

If you are using Azure DevOps pipeline, you may directly add the gradle task within it, see details here: [Trigger a test task run in the Hydra Lab test service](https://github.com/microsoft/HydraLab/wiki/Trigger-a-test-task-run-in-the-Hydra-Lab-test-service).

An alternative Azure DevOps extension is also available for ADO pipeline, if you want to test an iOS app (or Android app as well), you may search for extension "Hydra Lab" in ADO marketplace, and involve the task accordingly.
